### ISSUE TITLE
Python Debugging

### ISSUE THREAD

**Issue by steven-lang** [strottos/vim-padre#15]
Code sample with the breakpoint on the last line:

```python
def foo(bar):
    return bar + "baz"


s = foo("bar")               
```

Then run `:PadreDebug -t=python %` results in:

```
INFO: PADRE debugger open
INFO: Setting breakpoint in file foo.py at line number 5
ERROR: Error: {'status': 'PENDING'}
```

If I now press `r` for `Run` I get:

```
INFO: Launching process
ERROR: Timed out setting breakpoint
ERROR: Error: {'status': 'ERROR'} 
```

and in the lower tab padre states:

```
Listening on 0.0.0.0:46193      
warning: ignoring unknown option: -m
(lldb) target create "pdb"
error: unable to find executable for 'pdb'
Reading stdin error Error(Elapsed)
```

**Comment by strottos** [comment]
Yeah OK, good bug report, I'll take a look at some point. I'm pretty sure you can get over this with adding a `-d python3` (or full path name or whatever) for now but I will take a look at this as soon as I get chance. It basically thinks you want to use `lldb` incorrectly and its spawning the wrong debugger, all bets are off then, I will try and improve its auto recognising. Thanks.

**Comment by steven-lang** [comment]
Yes, it works when `-d=python3` is appended, thanks!

**Comment by strottos** [comment]
I believe this is now fixed, however if you're still seeing issues please do reopen and let me know.
